### ISSUE TITLE
Test failure on Elixir 1.2.1 / OTP 18

### ISSUE THREAD

**Issue by curiousleo** [LeeroyDing/json_logger#2]
All four tests fail on my machine:

```
$ elixir --version
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.2.1
```

```
$ mix test

=INFO REPORT==== 20-Jan-2016::23:18:36 ===
    application: logger
    exited: shutdown
    type: temporary


  1) test sends debug message via UDP (Logger.Backends.JSON.UDPTest)
     test/json_logger_udp_test.exs:21
     match (=) failed
     code: {:ok, {_ip, _port, message}} = :gen_udp.recv(server, 0, 500)
     rhs:  {:error, :timeout}
     stacktrace:
       test/json_logger_udp_test.exs:23



  2) test can change metadata (Logger.Backends.JSON.UDPTest)
     test/json_logger_udp_test.exs:30
     ** (exit) exited in: GenEvent.call(Logger, {Logger.Backends.JSON, :test}, {:configure, [metadata: "New metadata"]}, 5000)
         ** (EXIT) no process
     stacktrace:
       (elixir) lib/gen_event.ex:561: GenEvent.call/4
       test/json_logger_udp_test.exs:32



  3) test can use info level (Logger.Backends.JSON.UDPTest)
     test/json_logger_udp_test.exs:42
     ** (exit) exited in: GenEvent.call(Logger, {Logger.Backends.JSON, :test}, {:configure, [level: :info]}, 5000)
         ** (EXIT) no process
     stacktrace:
       (elixir) lib/gen_event.ex:561: GenEvent.call/4
       test/json_logger_udp_test.exs:43

?

  4) Logger.Backends.JSON.TCPTest: failure on setup_all callback, tests invalidated
     ** (exit) exited in: GenEvent.call(Logger, {Logger.Backends.JSON, :test}, {:configure, [level: :debug, metadata: "Very important data", output: {:tcp, "localhost", 38206}]}, 5000)
         ** (EXIT) no process
     stacktrace:
       (elixir) lib/gen_event.ex:561: GenEvent.call/4
       test/json_logger_tcp_test.exs:14: Logger.Backends.JSON.TCPTest.__ex_unit_setup_all_0/1
       test/json_logger_tcp_test.exs:1: Logger.Backends.JSON.TCPTest.__ex_unit__/2



Finished in 0.5 seconds (0.08s on load, 0.5s on tests)
4 tests, 4 failures, 1 invalid

Randomized with seed 594801
```

**Comment by LeeroyDing** [comment]
These tests are tricky to get all right. Looking into it.

**Comment by LeeroyDing** [comment]
If you're using this library in an active system, please tell me whether it actually works.

**Comment by curiousleo** [comment]
I'm not using the library in an active system. I was just looking around for a Logstash logger in Elixir, found this and ran the tests.

**Comment by LeeroyDing** [comment]
On Elixir 1.2.6 this issue's gone. If you're experiencing the problem in https://github.com/LeeroyDing/json_logger/issues/7 you're welcome to provide any information.
